include: "rules/common.smk"

rule all:
    input:
        generate_plots,
        expand([
                "results/{analysis_id}/crassus_results.tsv",
                ],
                sample=SAMPLES, analysis_id=ANALYSES_IDS)



include: "rules/assembly.smk"
include: "rules/scan_contigs.smk"
include: "rules/open_reading_frames.smk"
include: "rules/phylogenetic_trees.smk"
include: "rules/protein_clustering.smk"
include: "rules/assess_taxonomy.smk"
include: "rules/genomes_alignments.smk"
