sample_sheet: config/samples.tsv


mafft_msa:
  einsi: False


phylogenies:
  TerL: True
  MCP: True
  portal: True


shared_prots_cutoffs:
  family: 20
  genus: 65


plot:
  generate_plots: False
  aln_min_len: 200
